[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ovos-skill-iss-location"
dynamic = ["version"]
description = "info about where is the space station and astronauts on board"
readme = "README.md"
license = "Apache-2.0"
authors = [
    {name = "OpenVoiceOS", email = "jarbasai@mailfence.com"}
]
keywords = ["ovos", "skill", "plugin"]
dependencies = [
    "requests",
    "skyfield",
    "ovos-date-parser>=0.0.3,<1.0.0",
    "ovos-workshop>=8.0.0,<10.0.0",
    "ovos-bus-client>=1.0.1",
]

[project.optional-dependencies]
gui = [
    "matplotlib",
    "basemap",
    "pillow",
]
test = [
    "ovoscope>=1.11.2a1",
    "ovos-m2v-pipeline>=0.32.0a1",
    "ovos-adapt-parser>=1.0.9,<2.0.0",
    "pytest",
    "pytest-timeout",
]

[project.urls]
Homepage = "https://github.com/OpenVoiceOS/ovos-skill-iss-location"

[project.entry-points."ovos.plugin.skill"]
"ovos-skill-iss-location.openvoiceos" = "ovos_skill_iss_location:ISSLocationSkill"

[tool.setuptools]
packages = ["ovos_skill_iss_location"]
include-package-data = true

[tool.setuptools.package-dir]
ovos_skill_iss_location = ""

[tool.setuptools.dynamic]
version = {attr = "ovos_skill_iss_location.version.__version__"}

[tool.setuptools.package-data]
ovos_skill_iss_location = [
    "*.json",
    "locale/**/*",
    "gui/**/*",
    "res/**/*",
]
