name: Run UnitTests
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'version.py'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
      - 'scripts/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'version.py'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      matrix:
        python-version: [3.9, "3.10" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev
          python -m pip install build wheel
      - name: Install core repo
        run: |
          pip install .
      - name: Install test dependencies
        run: |
          pip install pytest pytest-timeout pytest-cov
      - name: Install System Dependencies
        run: |
          sudo apt-get update
      - name: Install ovos dependencies
        run: |
          pip install ovos-plugin-manager
      - name: Run unittests
        run: |
          pytest --cov=ovos-skill-iss-location --cov-report xml test
      - name: Upload coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        uses: codecov/codecov-action@v2
